routes/web.php
<?php

use App\Http\Controllers\Dashboard\Admin_PenyakitController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KonsultasiController;
use App\Http\Controllers\Dashboard\GejalaController;
use App\Http\Controllers\Dashboard\PenyakitController;

Route::get('/tes', function () {
    return view('components.dashboard');
});
Route::get('/', [HomeController::class,'index']);
Route::get('penyakit', [HomeController::class, 'penyakit'])->name('penyakit');
Route::get('penyakit/detail/{penyakit}', [HomeController::class,'detail'])->name('detail');
Route::get('gejala', [HomeController::class,'gejala'])->name('gejala');
Route::get('tentang', function(){
    return view('tentang');
})->name('tentang');

Route::group(['prefix' => 'konsultasi'], function () {
    Route::get('/' , [KonsultasiController::class,'pasienForm'])->name('pasienForm');
    Route::post('/', [KonsultasiController::class,'storeForm'])->name('storeForm');
    Route::post('diagnosa', [KonsultasiController::class,'diagnosa'])->name('diagnosa');
    Route::get('{pasien_id}/hasil', [KonsultasiController::class,'hasilDiagnosa'])->name('hasilDiagnosa');
});

Route::group(['prefix' => 'dashboard'], function() {
    Route::get('/', [Admin_PenyakitController::class,'dashboard']);
    Route::get('/penyakit', [Admin_PenyakitController::class,'index'])->name('admin.penyakit');
    Route::get('penyakit/{penyakit}/edit', [Admin_PenyakitController::class,'edit'])->name('penyakit.edit');
    Route::post('penyakit_store', [Admin_PenyakitController::class,'store'])->name('penyakit.store');
    Route::patch('penyakit_update/{penyakit}', [Admin_PenyakitController::class,'update'])->name('penyakit.update');
    Route::delete('penyakit_delete/{penyakit}', [Admin_PenyakitController::class,'destroy'])->name('penyakit.destroy');
    Route::get('/gejala', [GejalaController::class,'index'])->name('admin.gejala');
    Route::post('gejala', [GejalaController::class,'store'])->name('store');
    Route::patch('gejala_update/{gejala}', [GejalaController::class,'update'])->name('gejala.update');
    Route::delete('gejala_delete/{gejala}', [GejalaController::class,'destroy'])->name('gejala.destroy');
    Route::get('tentang', function(){
        return view('tentang');
    })->name('admin.tentang');
});

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     Route::get('/', [Admin_PenyakitController::class]);
// })->name('dashboard');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Dashboard
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="p-6">
                    <x-jet-application-logo />
                </div>
                <x-dashboard :pasien="$pasien" />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/diagnosa.blade.php
@extends('layouts.master')

@section('breadcrump')
<li><a href="{{ url('/') }}">Home</a></li>
<li><a href="{{ route('pasienForm') }}">Konsultasi</a></li>
<li class="active">Hasil Diagnosa</li>
@endsection

@section('content')
@include('layouts.aside')
<div class="col-md-9">
    <div class="panel panel-default">
    	<div class="panel-heading">
    		<strong>Hasil Diagnosa</strong>
    	</div>
    	<div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group col-md-12">
                        <label><strong>Data Diagnosa :</strong></label>
                    </div>
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-3">Nama</div>
                            <div class="col-md-9">: {{ $diagnosa->pasien->nama }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">Lokasi Pertanian</div>
                            <div class="col-md-9">: {{ $diagnosa->pasien->lokasi }}</div>
                        </div>
                        <hr>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group col-md-12">
                        <label><strong>Gejala yang nampak pada tanaman padi :</strong></label>
                    </div>
                </div>
                <div class="col-md-12">
                    <ol>
                    @foreach ($diagnosa->pasien->gejala as $gejala)
                        <li>{{ $gejala->nama }}</li>
                    @endforeach
                    </ol>
                    <hr>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group col-md-12">
                        <label><strong>Hasil Diagnosa :</strong></label>
                    </div>
                    <div class="col-md-12">
                        <p><strong>Tanaman Padi anda kemungkinan besar terkena penyakit {{ $diagnosa->penyakit->nama }}.</strong></p>
                        <div class="row">
                            <div class="col-md-2">
                                <label>Persentase :</label>
                            </div>
                            <div class="col-md-9">
                                <p>{{ $diagnosa->persentase }}%</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label>Definisi :</label>
                            </div>
                            <div class="col-md-9">
                                <p>{{ $diagnosa->penyakit->definis or 'Belum ada penjelasan lengkap mengenai penyakit ini.' }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <label>Penyebab :</label>
                            </div>
                            <div class="col-md-9">
                                <p>{{ $diagnosa->penyakit->penyebab }}</p>
                            </div>
                        </div>
                        <!-- <div class="row">
                            <div class="col-md-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <a href="javascript:;" data-toggle="collapse" data-target="#collapseOne">Kemungkinan Lainnya <i class="fa fa-fw fa-angle-down"></i></a>
                                    </div>
                                    <div id="collapseOne" class="panel-collapse collapse" aria-expanded="true">
                                        <div class="panel-body">
                                            <div class="col-md-12">
                                            @foreach ($diagnosa->pasien->diagnosa as $diagnosa)
                                                <div class="row">
                                                    <p><strong>{{ $diagnosa->penyakit->nama }}.</strong></p>
                                                    <div class="row">
                                                        <div class="col-md-2">
                                                            <label>Persentase :</label>
                                                        </div>
                                                        <div class="col-md-9">
                                                            <p>{{ $diagnosa->persentase }}%</p>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-md-2">
                                                            <label>Definisi :</label>
                                                        </div>
                                                        <div class="col-md-9">
                                                            <p>{{ $diagnosa->penyakit->definis or 'Belum ada penjelasan lengkap mengenai penyakit ini.' }}</p>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-md-2">
                                                            <label>Penyebab :</label>
                                                        </div>
                                                        <div class="col-md-9">
                                                            <p>{{ $diagnosa->penyakit->penyebab }}</p>
                                                        </div>
                                                    </div>
                                                    <br>
                                                </div>
                                            @endforeach
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> -->
                        <div class="row">
                            <div class="col-md-12">
                                <p>
                                    <!-- <button type="submit" class="btn btn-primary pull-right">Selesai <i class="fa fa-fw fa-sign-out"></i></button> -->
                                    @if ( Auth::user() )
                                        <a href="{{ url('/dashboard') }}" class="btn btn-primary pull-right">Selesai <i class="fa fa-fw fa-sign-out"></i></a>
                                    @else
                                        <a href="{{ url('/') }}" class="btn btn-primary pull-right">Selesai <i class="fa fa-fw fa-sign-out"></i></a>
                                    @endif
                                </p>
                            </div>
                            <hr>
                        </div>
                    </div>
                </div>
            </div>
    	</div>
    </div>
</div>
@endsection

resources/views/konsultasi_form_gejala.blade.php
@extends('layouts.master')

@section('breadcrump')
<li><a href="{{ url('/') }}">Home</a></li>
<li class="active">Konsultasi</li>
@endsection

@section('content')
@include('layouts.aside')
<div class="col-md-9">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Gejala</strong>
        </div>
        <div class="panel-body">
            <form method="POST" action="{{ route('diagnosa') }}">
                {{ csrf_field() }}
                <input type="hidden" name="pasien_id" value="{{ $pasien_id }}">
                <div class="form-group">
                    <label>Gejala-gejala yang nampak pada tanaman padi anda :</label>
                    <div class="col-md-12">
                        @foreach ($gejala as $gejala)
                            <div class="checkbox">
                                <label><input class="check" type="checkbox" name="gejala[]" value="{{ $gejala->id }}">{{ $gejala->nama }}</label>
                            </div>
                        @endforeach
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary pull-right">Cek Hasil Diagnonsa <i class="fa fa-fw fa-search"></i></button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/konsultasi_form_pasien.blade.php
@extends('layouts.master')

@section('breadcrump')
<li><a href="{{ url('/') }}">Home</a></li>
<li class="active">Konsultasi</li>
@endsection

@section('content')
@include('layouts.aside')
<div class="col-md-9">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Form Data Pasien</strong>
        </div>
        <div class="panel-body">
            <div class="col-md-10 col-md-offset-1">
                <form method="POST" action="{{ route('storeForm') }}">
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Nama :</label>
                                <input type="text" name="nama" class="form-control" required="required" placeholder="Nama pasien / petani...">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Lokasi :</label>
                                <textarea class="form-control" name="lokasi" required="required" placeholder="Lokasi pertanian..."></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <p><button type="submit" class="btn btn-primary pull-right">Mulai Konsultasi <i class="fa fa-fw fa-sign-in" aria-hidden="true"></i></button></p>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="clearfix" style="margin-bottom: 20px;"></div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tentang.blade.php
<x-guest-layout>
    <x-jet-authentication-card>
        <x-slot name="logo">
            <x-jet-authentication-card-logo />
        </x-slot>
        <x-jet-action-section>
            <x-slot name="title">
                SISTEM PAKAR
            </x-slot>
            <x-slot name="description">
                Tugas Tambahan Pembuatan Sistem Pakar Padi
            </x-slot>
            <x-slot name="content">
                <table class="table table-light">
                    <tbody>
                        <tr>
                            <td>Nama</td>
                            <td>:</td>
                            <td>Faisal</td>
                        </tr>
                        <tr>
                            <td>Kelas</td>
                            <td>:</td>
                            <td>VII C</td>
                        </tr>
                        <tr>
                            <td>Program Studi</td>
                            <td>:</td>
                            <td>Teknologi Rekayasa Perangkat Lunak</td>
                        </tr>
                    </tbody>
                </table>
            </x-slot>
        </x-jet-action-section>
    </x-jet-authentication-card>
</x-guest-layout>